import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "@/components/section/Navbar";
import Footer from "@/components/section/Footer";
import Providers from "@/components/Provider";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Eccomerce Next App",
  description: "Generated by Muneeb Ullah",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <Providers>
            <NavBar />
            {children}
            <Footer />
          </Providers>
        </ClerkProvider>
      </body>
    </html>
  );
}
